Update dependencies
sul-dlss/exhibits pull request #1989
Opened 2021-02-12 00:45 UTC by cbeer

2021-02-22 20:16 UTC, mejackreed requested changes
Nice job on this! This is working well for me. I took the Parker bibtex and annotation stuff and noticed another `try` here: https://github.com/sul-dlss/exhibits/blob/master/app/models/feature_flags.rb#L23

Also, there seem to be two more `try`s. Do we need to update those also?

Besides that everything is working well for me.

2021-02-22 20:35 UTC, mejackreed approved these changes

2021-02-22 23:16 UTC, mejackreed commented on lib/traject/dor_config.rb
> +to_field 'manuscript_number_tesim', (accumulate { |resource, *_| resource.smods_rec.location.shelfLocator&.text })
Should there be a `respond_to?` in here also?

2021-02-25 18:00 UTC, jkeck reviewed
Quick Q, otherwise @camillevilla and I have reviewed and looks good.

2021-02-25 18:02 UTC, camillevilla approved these changes

2021-02-25 18:04 UTC, cbeer commented on config/initializers/spotlight_initializer.rb
> +      message = exception.inspect.truncate(1.megabyte)
This is the first I've run into `truncate_bytes `, but, yeah, 1mb of characters was the intent. It was:

https://github.com/sul-dlss/exhibits/pull/1989/files#diff-f992e55b881f855664e3a8c00a859308530b3c11edc9bce46890f29868ea8db9L131

but 1000 character was never enough to be useful 🤷‍♂️

2021-02-25 18:31 UTC, jkeck commented on config/initializers/spotlight_initializer.rb
> +      message = exception.inspect.truncate(1.megabyte)
Ah, looks like #truncate_bytes was introduced in rails 6 FWIW.  It seems like that would be a lot of data, even after truncation, but if that's what you want :shipit:

2021-02-25 18:31 UTC, jkeck approved these changes

2021-02-25 18:31 UTC, merged