initial commit
sul-dlss/exhibits pull request #2752
Opened 2024-12-17 18:23 UTC by dnoneill

2025-01-24 18:43 UTC, dnoneill commented on config/initializers/oembed.rb
> +purl_provider = OEmbed::Provider.new('https://sul-purl-stage.stanford.edu/embed.{format}?&hide_title=true')
```suggestion
purl_provider = OEmbed::Provider.new('https://sul-purl-stage.stanford.edu/embed.{format}?&hide_title=true')
purl_provider = OEmbed::Provider.new('http://localhost:3001/embed.{format}?&hide_title=true')
```

for testing locally

2025-01-24 18:45 UTC, dnoneill commented on config/settings.yml
> +  url: https://embed-stage.stanford.edu/iiif
```suggestion
  url: https://embed-stage.stanford.edu/iiif
  url: http://localhost:3001.stanford.edu/iiif
```
For testing locally

2025-01-24 19:39 UTC, jcoyne requested changes

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +  global.RequestViewerState = RequestViewerState;
Why do we need to set this? Can we just import the `init` function?

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +  var RequestViewerState;
Why do we need a var?  can you just put const on the next line?

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/select_image_area.js
> +  var SelectImageArea;
why does this need to be a var?  can we just put const on the next line?

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/select_image_area.js
> +  global.SelectImageArea = SelectImageArea;
Can we just import the init function?

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/spotlight.js
> +//= require select_image_area
Are we able to do this without continuing to use Sprockets?  Sprockets is deprecated, so that just seems to dig us deeper into debt.

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/select_image_area.js
> +Blacklight.onLoad(function () {
Is there a reason we need to depend on `Blacklight` here?

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +Blacklight.onLoad(function () {
Is there a reason we need to depend on `Blacklight` here? Won't this create a duplicate event listener on every pageview (assuming turbo or turbolinks is used).

2025-01-24 19:39 UTC, jcoyne commented on app/assets/javascripts/select_image_area.js
> +  document.querySelectorAll('#page-content').forEach(function(element, i) {
Why do we need a `querySelectorAll` on an id?  Id should be unique, so `getElementById` should be used.

2025-01-27 23:24 UTC, hudajkhan commented
I tried this out with the sul-embed branch, and this feature works as intended.

2025-01-28 22:05 UTC, dnoneill commented on app/assets/javascripts/request_viewer_state.js
> +  global.RequestViewerState = RequestViewerState;
This seems to be how we are doing it in all our JS. If you have specific code I can plug in to test to see if it works then I will do that, but otherwise I do not think it is worth the time it will take me to figure it out. Especially since this is inline with what we are doing in this application. 

https://github.com/sul-dlss/exhibits/blob/main/app/assets/javascripts/bibliography.js#L101
https://github.com/sul-dlss/exhibits/blob/main/app/assets/javascripts/nested_related_items.js#L86

2025-01-28 22:08 UTC, dnoneill commented on app/assets/javascripts/request_viewer_state.js
> +Blacklight.onLoad(function () {
Nope. cruft from before we figured out the blacklight-modal event

2025-01-28 22:35 UTC, hudajkhan commented on app/assets/javascripts/spotlight.js
> +//= require select_image_area
That sounds correct @dnoneill

2025-01-28 23:02 UTC, dnoneill commented on app/assets/javascripts/select_image_area.js
> +  global.SelectImageArea = SelectImageArea;
see above

2025-01-28 23:02 UTC, dnoneill commented on app/assets/javascripts/select_image_area.js
> +Blacklight.onLoad(function () {
doesn't work without it.

2025-01-29 14:37 UTC, jcoyne requested changes

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +/* global Blacklight */
Where is Blacklight used here?

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/select_image_area.js
> +/* global Blacklight */
Where is Blacklight used here?

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +  global.RequestViewerState = RequestViewerState;
All of this JS was written 10 years ago, pre ES2015 standard.  Just because it's been that way in the past, doesn't mean we should repeat those patterns.

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/select_image_area.js
> +Blacklight.onLoad(function () {
Blacklight.onLoad is just a thin wrapper around `document.addEventListener("DOMContentLoaded", ...`

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/spotlight.js
> +//= require select_image_area
I'm pretty sure these can be loaded independently (via importmap), since they have no dependency on anything within Spotlight.

2025-01-29 14:37 UTC, jcoyne commented on app/views/catalog/_embedded_mirador3.html.erb
> +        src: "#{Settings.iiif_embed.url}?#{{ url: manifest_url, canvas_id: choose_canvas_id(block) || params[:canvas_id], iiif_initial_viewer_config: choose_initial_viewer_config(block) || params[:ii
This is a lot of code for an erb file.  Can this be turned into a ViewComponent, so that some of this can be plain ruby methods?

2025-01-29 14:37 UTC, jcoyne commented on app/controllers/catalog_controller.rb
> +  def select_image_area
This controller is already doing too many things.  Please move this to a new controller that is about "image areas".

2025-01-29 14:37 UTC, jcoyne commented on config/initializers/oembed.rb
> +#purl_provider = OEmbed::Provider.new('http://purl.stanford.edu/embed.{format}?&hide_title=true')
Should this be reverted?

2025-01-29 14:37 UTC, jcoyne commented on config/settings.yml
> +  url: https://embed-stage.stanford.edu/iiif
The place for local values is  `config/settings/developement.yml`

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +                    console.log('Exhibits: received state:', parsedData.data);
Please extract this block to a separate method. The outer method is very long and hard to fully understand.

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +                    const canvasField = document.querySelector(`#${this.formId} > input[name="item[${this.itemId}][iiif_canvas_id]"]`)
Can you do 
```
const formNode = document.getElementById(this.formId);
formNode.querySelector("input[name="item[${this.itemId}][iiif_canvas_id]")
```

2025-01-29 14:37 UTC, jcoyne commented on app/assets/javascripts/request_viewer_state.js
> +                    const iiif_initial_viewer_config = JSON.stringify(viewers[viewer]);
Use camel case variable names for javascript.

2025-01-29 15:38 UTC, dnoneill commented on config/initializers/oembed.rb
> +#purl_provider = OEmbed::Provider.new('http://purl.stanford.edu/embed.{format}?&hide_title=true')
Yeah the stage stuff is just for deploying to stage for users to test.

2025-01-29 16:34 UTC, dnoneill commented on app/views/catalog/_embedded_mirador3.html.erb
> +        src: "#{Settings.iiif_embed.url}?#{{ url: manifest_url, canvas_id: choose_canvas_id(block) || params[:canvas_id], iiif_initial_viewer_config: choose_initial_viewer_config(block) || params[:ii
I think that is outside the scope of this very large PR. Can move this into a helper method but I think moving this into a ViewComponent should be it's own PR. I think if we are going to move this into a ViewComponent we should also move https://github.com/sul-dlss/exhibits/blob/dff44d8436cec0e9d950f4bf501b1228a03b9c4a/app/views/catalog/_oembed_default.html.erb into a ViewComponent. So I think that should be it's own PR.

2025-01-29 16:46 UTC, jcoyne commented on config/initializers/oembed.rb
> +#purl_provider = OEmbed::Provider.new('http://purl.stanford.edu/embed.{format}?&hide_title=true')
Can you put this in a config/settings.yml and use shared config for this?

2025-01-29 17:09 UTC, dnoneill commented on app/assets/javascripts/request_viewer_state.js
> +  global.RequestViewerState = RequestViewerState;
If you have specific code I can plug in to test to see if it works then I will do that, but otherwise I do not think it is worth the time it will take me to figure it out. We only have til the end of this week to get this into exhibits and it is a priority.

2025-01-29 17:09 UTC, dnoneill commented on app/assets/javascripts/select_image_area.js
> +Blacklight.onLoad(function () {
Are you suggesting using document.addEventListener("DOMContentLoaded" instead?

2025-01-29 17:36 UTC, taylor-steve commented on app/assets/javascripts/spotlight.js
> +//= require select_image_area
@jcoyne is correct, we could definitely handle this with an importmap now, it works fine with sprockets and isn't dependent on Spotlight. 

We could also incorporate this into the upcoming jsbundling work, I think that'd be a fine approach as well.

It looks like we might want to update the JS slightly for either approach, I will add to those specific discussions.

2025-01-29 17:43 UTC, dnoneill commented on app/controllers/catalog_controller.rb
> +  def select_image_area
This is taking more than an hour to figure out. I am getting can can errors, etc.

2025-01-31 17:18 UTC, dnoneill commented on app/assets/javascripts/select_image_area.js
> +Blacklight.onLoad(function () {
It doesn't work. I tried multiple iterations of DOMContentLoaded and it didn't work. I am guessing it is due to Spotlight waiting for Blacklight to load and this code is dependent on Spotlight JS running.
https://github.com/projectblacklight/spotlight/blob/5384fca74a40faf5e214900afab44733ed67fb6e/lib/generators/spotlight/assets/importmap_generator.rb#L62-L64

2025-02-13 21:46 UTC, merged